---
title: "CellChat2"
author: "Anan"
date: "2024-03-31"
output: html_document
#https://www.jianshu.com/p/03f9c2f3ee4f?utm_campaign=hugo&utm_medium=reader_share&utm_content=note
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
 library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
library(curl)
```


```{r}
# Here we load a scRNA-seq data matrix and its associated cell meta data
#load(url("https://ndownloader.figshare.com/files/25950872")) # This is a combined data #from two biological conditions: normal and diseases
#data.input = data_humanSkin$data # normalized data matrix
#meta = data_humanSkin$meta # a dataframe with rownames containing cell mata data
#cell.use = rownames(meta)[meta$condition == "LS"] # extract the cell names from disease data

# Prepare input data for CelChat analysis
#data.input = data.input[, cell.use]
#meta = meta[cell.use, ]
# meta = data.frame(labels = meta$labels[cell.use], row.names = colnames(data.input)) # manually create a dataframe consisting of the cell labels
#unique(meta$labels) # check the cell labels
#>  [1] Inflam. FIB  FBN1+ FIB    APOE+ FIB    COL11A1+ FIB cDC2        
#>  [6] LC           Inflam. DC   cDC1         CD40LG+ TC   Inflam. TC  
#> [11] TC           NKT         
#> 12 Levels: APOE+ FIB FBN1+ FIB COL11A1+ FIB Inflam. FIB cDC1 cDC2 ... NKT
```

```{r}
# 安装curl包（如果你还没有安装的话）
# install.packages("curl")

# 加载curl包
#library(curl)

# 设置要下载的URL
#url <- "https://ndownloader.figshare.com/files/25950872"

# 设置保存文件的路径和文件名
#save_path <- "data_humanSkin_CellChat.rda"

# 使用curl_download()函数下载文件
#curl::curl_download(url, save_path)


```
```{r}
# Here we load a scRNA-seq data matrix and its associated cell meta data
##load(url("https://ndownloader.figshare.com/files/25950872")) # This is a combined data from two biological conditions: normal and diseases
#data.input = data_humanSkin$data # normalized data matrix
#meta = data_humanSkin$meta # a dataframe with rownames containing cell mata data
#cell.use = rownames(meta)[meta$condition == "LS"] # extract the cell names from disease data

# Prepare input data for CelChat analysis
#data.input = data.input[, cell.use]
#meta = meta[cell.use, ]
# meta = data.frame(labels = meta$labels[cell.use], row.names = colnames(data.input)) # manually create a dataframe consisting of the cell labels
#unique(meta$labels) # check the cell labels
#>  [1] Inflam. FIB  FBN1+ FIB    APOE+ FIB    COL11A1+ FIB cDC2        
#>  [6] LC           Inflam. DC   cDC1         CD40LG+ TC   Inflam. TC  
#> [11] TC           NKT         
#> 12 Levels: APOE+ FIB FBN1+ FIB COL11A1+ FIB Inflam. FIB cDC1 cDC2 ... NKT
```


```{r}
#cellchat <- createCellChat(object = data.input, meta = meta, group.by = "labels")
#> Create a CellChat object from a data matrix
#> Set cell identities for the new CellChat object
#> The cell groups used for CellChat analysis are  APOE+ FIB FBN1+ FIB COL11A1+ FIB Inflam. FIB cDC1 cDC2 LC Inflam. DC TC Inflam. TC CD40LG+ TC NKT
```

```{r}
#cellchat <- addMeta(cellchat, meta = meta)
#cellchat <- setIdent(cellchat, ident.use = "labels") # set "labels" as default cell identity
#levels(cellchat@idents) # show factor levels of the cell labels
#groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
```



```{r}
#CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
#showDatabaseCategory(CellChatDB)
```


```{r}
# Show the structure of the database
#dplyr::glimpse(CellChatDB$interaction)
#> Rows: 1,939
#> Columns: 11
#> $ interaction_name   <chr> "TGFB1_TGFBR1_TGFBR2", "TGFB2_TGFBR1_TGFBR2", "TGF…
#> $ pathway_name       <chr> "TGFb", "TGFb", "TGFb", "TGFb", "TGFb", "TGFb", "T…
#> $ ligand             <chr> "TGFB1", "TGFB2", "TGFB3", "TGFB1", "TGFB1", "TGFB…
#> $ receptor           <chr> "TGFbR1_R2", "TGFbR1_R2", "TGFbR1_R2", "ACVR1B_TGF…
#> $ agonist            <chr> "TGFb agonist", "TGFb agonist", "TGFb agonist", "T…
#> $ antagonist         <chr> "TGFb antagonist", "TGFb antagonist", "TGFb antago…
#> $ co_A_receptor      <chr> "", "", "", "", "", "", "", "", "", "", "", "", ""…
#> $ co_I_receptor      <chr> "TGFb inhibition receptor", "TGFb inhibition recep…
#> $ evidence           <chr> "KEGG: hsa04350", "KEGG: hsa04350", "KEGG: hsa0435…
#> $ annotation         <chr> "Secreted Signaling", "Secreted Signaling", "Secre…
#> $ interaction_name_2 <chr> "TGFB1 - (TGFBR1+TGFBR2)", "TGFB2 - (TGFBR1+TGFBR2…

# use a subset of CellChatDB for cell-cell communication analysis
#CellChatDB.use <- subsetDB(CellChatDB, search = "Secreted Signaling") # use Secreted Signaling
# use all CellChatDB for cell-cell communication analysis
# CellChatDB.use <- CellChatDB # simply use the default CellChatDB

# set the used database in the object
#cellchat@DB <- CellChatDB.use
```

```{r}
#cellchat <- subsetData(cellchat) # subset the expression data of signaling genes for saving computation cost
#future::plan("multicore", workers = 4) # do parallel
#> Warning: [ONE-TIME WARNING] Forked processing ('multicore') is disabled
#> in future (>= 1.13.0) when running R from RStudio, because it is
#> considered unstable. Because of this, plan("multicore") will fall
#> back to plan("sequential"), and plan("multiprocess") will fall back to
#> plan("multisession") - not plan("multicore") as in the past. For more details,
#> how to control forked processing or not, and how to silence this warning in
#> future R sessions, see ?future::supportsMulticore
#cellchat <- identifyOverExpressedGenes(cellchat)
#cellchat <- identifyOverExpressedInteractions(cellchat)
#cellchat <- projectData(cellchat, PPI.human)
```

```{r}
#cellchat <- computeCommunProb(cellchat, raw.use = TRUE)
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
#cellchat <- filterCommunication(cellchat, min.cells = 10)
```


```{r}
#cellchat <- computeCommunProbPathway(cellchat)
```


```{r}
#cellchat <- aggregateNet(cellchat)
```


```{r}
#groupSize <- as.numeric(table(cellchat@idents))
#par(mfrow = c(1,2), xpd=TRUE)
#netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
#netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
```


```{r}
#pathways.show <- c("CXCL") 
 #Hierarchy plot# Here we define `vertex.receive` so that the left portion of the hierarchy plot shows signaling to fibroblast and the right portion shows signaling to immune cells
#vertex.receiver = seq(1,4) # a numeric vector. 
#netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver)
```


```{r}
#Circle plotpar(mfrow=c(1,1))
#netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```


```{r}
# Chord diagrampar(mfrow=c(1,1))
#netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```

```{r}
# Heatmappar(mfrow=c(1,1))
#netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")#> Do heatmap based on a single object
```


```{r}
#Chord diagram
#group.cellType <- c(rep("FIB", 4), rep("DC", 4), rep("TC", 4)) # grouping cell clusters into fibroblast, DC and TC cells
#names(group.cellType) <- levels(cellchat@idents)
#netVisual_chord_cell(cellchat, signaling = pathways.show, group = group.cellType, title.name = paste0(pathways.show, " signaling network"))
#> Plot the aggregated cell-cell communication network at the signaling pathway level#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```

```{r}
#netAnalysis_contribution(cellchat, signaling = pathways.show)
```


```{r}
#pairLR.CXCL <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
#LR.show <- pairLR.CXCL[1,] # show one ligand-receptor pair
# Hierarchy plotvertex.receiver = seq(1,4) 
# a numeric vector
#netVisual_individual(cellchat, signaling = pathways.show,  pairLR.use = LR.show, vertex.receiver = vertex.receiver)
```


```{r}
# Circle plot
#netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "circle")
```


```{r}
#> [[1]]# Chord diagram
#netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "chord")#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```


```{r}
# Access all the signaling pathways showing significant communications
#pathways.show.all <- cellchat@netP$pathways# check the order of cell identity to set suitable vertex.
#receiverlevels(cellchat@idents)
#vertex.receiver = seq(1,4)
#for (i in 1:length(pathways.show.all)) 
#  {  # Visualize communication network associated with both signaling pathway and individual L-R pairs  
#netVisual(cellchat, signaling = pathways.show.all[i], vertex.receiver = vertex.receiver, layout = "hierarchy")  
# Compute and visualize the contribution of each ligand-receptor pair to the overall signaling pathway  
#gg <- netAnalysis_contribution(cellchat, signaling = pathways.show.all[i])  #ggsave(filename=paste0(pathways.show.all[i], "_L-R_contribution.pdf"), plot=gg, width = 3, height = 2, units = 'in', dpi = 300)}
```







